<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Pixnop.Atlas.XUnit" Version="0.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ArcanumLib.csproj">
      <AtlasMod>true</AtlasMod>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)\VintagestoryAPI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VINTAGE_STORY)\VintagestoryLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(VINTAGE_STORY)\Lib\cairo-sharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VINTAGE_STORY)\Lib\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VINTAGE_STORY)\Lib\protobuf-net.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SkiaSharp">
      <HintPath>$(VINTAGE_STORY)\Lib\SkiaSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(VINTAGE_STORY)\Lib\libSkiaSharp.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <Content Include="fixtures\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Atlas.Api" />
    <Using Include="Atlas.XUnit" />
  </ItemGroup>

</Project>
